# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: download checkstyle
        run: curl -o checkstyle.jar -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.40/checkstyle-8.40-all.jar
      - name: checkstyle
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: java -jar checkstyle.jar -c ${{ github.workspace }}/checkstyle-config.xml -f xml src | reviewdog -f=checkstyle -name="Checkstyle" -reporter=github-check
  build:
    needs: [checkstyle]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: |
          mvn -B package -DskipTests --file pom.xml
          mkdir ${{ github.workspace }}/package
          cp ${{ github.workspace }}/javamesh-agent-2.0.5.tar ${{ github.workspace }}/package
      - name: upload package
        uses: actions/upload-artifact@v1
        with:
          name: java-mesh
          path: ${{ github.workspace }}/package

